import Head from "next/head";
import { Button, HStack, Img, Switch, VStack } from "@chakra-ui/react";
import Router from "next/router";
import { useState } from "react";

export default function Home() {
  const [dark, setDark] = useState(false);
  let logo = 'projectUNO.png'
  return (
    <>
      <Head>
        <title>Mikmik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack 
      color = {dark ? 'white':'black'}
      bgImg= {dark? "/DarkMode.jpg": "/LightMode.jpg"}
      bgSize="100%"
      width="100%"
      height="100vh"
      >
      <HStack 
      mt='8'
      justifyContent={"space-between"}
      spacing="1100"
      >
         <HStack justifyContent={'flex-start'}>
         <Img    
          h='50'
          w='15vh'
          src = {logo}/>
        <Switch
                  paddingTop={"1"}
                  colorScheme={"teal"}
                  size={"md"}
                  onChange={() => setDark(!dark)}
                />
        </HStack>

        <HStack justifyContent="flex-end" spacing="5">
        <Button 
        colorScheme="darkcyan"
        onClick={() => Router.push({ pathname: "/profile" })}>
          Profile
          </Button>
        <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/" })}>
          Log out
        </Button>
        </HStack>
      </HStack>
      </VStack>
    </>
  );
}
