import Head from "next/head";
import { Button, Container, Heading, HStack, Img, Switch, VStack } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import Router from "next/router";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [dark, setDark] = useState(false);
  return (
    <>
      <Head>
        <title>Mikmik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack 
      bgImg= {dark? "/DarkMode.jpg": "/LightMode.jpg"}
      bgSize="100%"
      width="100%"
      height="100vh"
      >
      <HStack 
      justifyContent={"space-between"}
      spacing="900" 
      mt="3" 
      ml="200" >
        <HStack justifyContent={'flex-start'}>
        <Switch
                  paddingTop={"1"}
                  colorScheme={"teal"}
                  size={"md"}
                  onChange={() => setDark(!dark)}
                />
        </HStack>

        <HStack justifyContent="flex-end" spacing="5">
        <Img borderRadius='full'
          boxSize='40px'
          src = '/Mikmik.jpg'
          alt='Dan Abramov'
        />  
        <Button 
        colorScheme="darkcyan"
        onClick={() => Router.push({ pathname: "/Profile" })}>
          Sign-in
          </Button>
        <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/signup" })}>
          Sign-up
        </Button>
        <Button colorScheme="DarkCyan">Logout</Button>
        </HStack>
      </HStack>
      </VStack>
    </>
  );
}
