
import { Button, Center, Heading, HStack, Text, } from '@chakra-ui/react'
import Head from 'next/head'
import  Router  from 'next/router'

export default function Profile(){
    let firstName = 'John Michael'
    return(
        <><Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    <Center><Heading>Profile tab</Heading></Center>
    <Center><Text>Name: {firstName} </Text></Center>
    <HStack 
      justifyContent={"space-between"} 
      mt="3" 
      mr="2" >
        <HStack> 
          <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/" })}
        >
          Home
        </Button>

        </HStack>
        <HStack justifyContent="flex-end" spacing="5">

        <Button 
        colorScheme="darkcyan">Sign-in</Button>

        <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/signup" })}>
          Sign-up
        </Button>

        <Button colorScheme="DarkCyan">Logout</Button>

        </HStack>
      </HStack>
        </>
    )
}