
import { Img, Button, Center, Heading, HStack, Switch, Text, VStack, } from '@chakra-ui/react'
import Head from 'next/head'
import  Router  from 'next/router'
import { useState } from 'react';

export default function Profile(){
  const [dark, setDark] = useState(false);
    let firstName = 'John Michael'
    return(
        <><Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <VStack 
      bgImg= {dark? "/DarkMode.jpg": "/LightMode.jpg"}
      bgSize="100%"
      width="100%"
      height="100vh"
      >
      <HStack 
      justifyContent={"space-between"}
      spacing="1050" 
      mt="3" 
      mr="2" >
        <HStack justifyContent={'flex-start'}>
        <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/" })}
        >
          Home
        </Button>
        <Switch
                  paddingTop={"1"}
                  colorScheme={"teal"}
                  size={"md"}
                  onChange={() => setDark(!dark)}
                />
        </HStack>
        
        <HStack justifyContent="flex-end" spacing="5">
        <Text as='b'>John Michael Amican</Text>
        <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/" })}>
          Logout
        </Button>
        </HStack>
      </HStack>
      </VStack>
        </>
  );
}