import { Img, Button, HStack, Switch, Text, VStack, useDisclosure, Modal, ModalCloseButton, ModalContent, ModalOverlay, } from '@chakra-ui/react'
import Head from 'next/head'
import  Router  from 'next/router'
import { useState } from 'react';

export default function Profile(){
    const { isOpen, onOpen, onClose } = useDisclosure()
    const [dark, setDark] = useState(false);
    let firstName = 'John Michael'
    let surName = 'Amican'
    let profilePic = '/Mikmik.jpg'
    return(
        <><Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      <VStack 
      color = {dark ? 'white':'black'}
      bgImg= {dark? "/DarkMode.jpg": "/LightMode.jpg"}
      bgSize="100%"
      width= "100%"
      height= "100vh"
      overflow = 'hidden'
      >
      <HStack 
      mt="10"
      justifyContent={"space-between"}
      spacing="1000" 
    >
        <HStack justifyContent={'flex-start'}
        >
        <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/" })}
        >
            Home
        </Button>
        <Switch
                  paddingTop={"1"}
                  colorScheme={"teal"}
                  size={"md"}
                  onChange={() => setDark(!dark)}
                />
        </HStack>
        
        <HStack 
        mr="10"
        justifyContent="flex-end" 
        spacing="5">
        <Text
        _hover={{cursor:'pointer',color:'darkblue', transform:'scale(1.2)', transitionDuration:'.2s'}}
        onClick={() => Router.push({ pathname: "https://www.facebook.com/Mikmikey24/" })}
        as='b'>
        {firstName+' '+surName}</Text>
        <Img borderRadius='full'
          boxSize='35px'
          src = {profilePic}
          onClick={onOpen}
          alt='Mikmik'
        />      
        <Button
          colorScheme="DarkCyan"
          onClick={() => Router.push({ pathname: "/" })}>
          Logout
        </Button>
        </HStack>
      </HStack>
      </VStack>
        <Modal 
        isOpen={isOpen} onClose={onClose}>
        <ModalOverlay/>
        <ModalContent borderRadius='full'>
        <ModalCloseButton color='white'/>
        <Img
        borderRadius='2%'
          boxSize='100%'
          src = {profilePic}
          alt='Mikmik'
        />      
        </ModalContent>
        </Modal>
        </>
  );
}